var_density: Gaussian
seed_no: 5
## physical parameters
img_size: 32
min_value: 0
max_value: 4
test_img_index: 110
noise_var: 1.0
like_var: 1.0
k: 0.064
## GAN-specific parameters
latent_dim: 5
## VI-specific parameters
xi_sampling: "nonuniform_deterministic"
n_iter: 60000
batch_size: 25
elbo_batch_size: 2000
mu_init_scalar: 0.015
sigma_init_scalar: -0.917
mu_step_size: 5.e-3
gamma_step_size: 5.e-3
epsilon: 1.e-7
# type of optimizer
optimizer: "gradient_descent"
# posterior stats parameters
n_samples: 50000
## MCMC parameters
n_mcmc_samples: 100000
mcmc_prop_var: 1
burn_in: 0.5
hmc_epsilon: 0.00001
hmc_n_lf_steps: 2