var_density: Gaussian
seed_no: 5
## physical parameters
box_z_dim: 40
box_x_dim: 80
min_value: 0.0161
max_value: 0.26
like_var: 705
n_pressure_sensors: 47
n_source_sensors: 9
## GAN-specific parameters
latent_dim: 50
gan_dim: 8
## CNNsurrogate-specific parameters
cnn_dim: 4
## VI-specific parameters
xi_sampling: "normal_symmetric"
n_iter: 200
batch_size: 150
elbo_batch_size: 2000
mu_init_scalar: 0.015
sigma_init_scalar: -0.5
mu_step_size: 5.e-3
gamma_step_size: 1.e-2
epsilon: 1.e-7
# type of optimizer
optimizer: "adam"
# posterior stats parameters
n_samples: 50000
## MCMC parameters
n_mcmc_samples: 2800
mcmc_prop_var: 0.75
burn_in: 0.5
hmc_epsilon: 0.00001
hmc_n_lf_steps: 2