target_density: NonGaussian
var_density: Gaussian
x_dim: 1
# VI-specific parameters
n_iter: 40
mu_step_size: 0.2
gamma_step_size: 0.05  
batch_size: 20  
mu_init_scalar: 0
gamma_init_scalar: 1.1 
epsilon: 1.e-8
# type of optimizer
optimizer: "adam"